### PR TITLE
Add healthchecks into docker-compose.yml

### PR DESCRIPTION
**Pull request by haphut**
Add healthchecks into `docker-compose.yml` so that the frontend is functional immediately after startup.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/22)

### CODE REVIEW

**Review by pallost — APPROVED** [review]

**Comment by tk-vincit** [comment]
En juuri nyt ehdi kaivaa tähän liittyvää linkkiä, mutta olen 99% varma että kun selvittelin tätä eilen niin törmäsin juttuun jonka mukaan healtcheck oli deprekoitu dockerfilen 3.jotain versiossa, koska sitä ei pidetty hyvänä käytäntönä. Eli tämä ei todennäköisesti toimi.

**Review by pallost — APPROVED** [review]
Mun silmällä näyttää hyvältä ja olen jo käyttänyt tämmöstä parametrisointia. Jos toimii, pistäkää sisään. Jos ei, hylätään pull requ

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/22#-:-MVQccYGB80YrBPuhdhw:b5zyxxm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tk-vincit)

**Comment by haphut** [comment]
I wrote this script into the directory `frontend` and ran it:

```bash
#!/bin/bash
#
# Warning: Generates many stdout_* and stderr_* files.

while true; do
  timestamp="$(date --utc '+%Y%m%dT%H%M%SZ')"
  echo "start graphqurl at ${timestamp}"
  yarn run graphqurl "http://localhost:8080/v1beta1/relay" --introspect \
    1> "stdout_${timestamp}" \
    2> "stderr_${timestamp}"
  echo "yarn run graphqurl exit code: $?"
  sleep 1
done
```

Then I ran `docker-compose up --build`. First `yarn run graphqurl` reported, in order:
```
Error:  ApolloError: Network error: request to http://localhost:8080/v1beta1/relay failed, reason: connect ECONNREFUSED 127.0.0.1:8080
...
Error:  ApolloError: Network error: request to http://localhost:8080/v1beta1/relay failed, reason: read ECONNRESET
...
Error:  ApolloError: Network error: request to http://localhost:8080/v1beta1/relay failed, reason: socket hang up
  (This one is also ECONNRESET.)
```

Finally the script succeeded in fetching the schema successfully on the same second that hasura logged this:
```
hasura_1    | {"type":"startup","timestamp":"2021-03-10T12:01:01.690+0000","level":"info","detail":{"kind":"catalog_migrate","info":"Already at the latest catalog version (40); nothing to do."}}
hasura_1    | {"type":"startup","timestamp":"2021-03-10T12:01:01.690+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 26","instance_id":"6c22ebdf-d4b2-4753-a51e-842a7c4c3c24","message":"listener thread started"}}}
hasura_1    | {"type":"startup","timestamp":"2021-03-10T12:01:01.690+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 27","instance_id":"6c22ebdf-d4b2-4753-a51e-842a7c4c3c24","message":"processor thread started"}}}
hasura_1    | {"type":"startup","timestamp":"2021-03-10T12:01:01.690+0000","level":"info","detail":{"kind":"event_triggers","info":"preparing data"}}
hasura_1    | {"type":"startup","timestamp":"2021-03-10T12:01:01.690+0000","level":"info","detail":{"kind":"event_triggers","info":"starting workers"}}
hasura_1    | {"type":"startup","timestamp":"2021-03-10T12:01:01.690+0000","level":"info","detail":{"kind":"scheduled_triggers","info":"preparing data"}}
hasura_1    | {"type":"startup","timestamp":"2021-03-10T12:01:01.690+0000","level":"info","detail":{"kind":"server","info":{"time_taken":6.478024869,"message":"starting API server"}}}
hasura_1    | {"type":"http-log","timestamp":"2021-03-10T12:01:01.690+0000","level":"info","detail":{"operation":{"query_execution_time":6.0569118e-2,"user_vars":{"x-hasura-role":"anonymous"},"request_id":"d32293ad-40ab-478d-b92f-226bab89c100","response_size":4933,"request_read_time":3.556e-6},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1beta1/relay","ip":"172.24.0.1","method":"POST","content_encoding":"gzip"}}}
```

Based on this information hasura publishes the API immediately after it is done with its initialization.

I assume that the reason for the `socket hang up` error is that at some point before finishing the initialization hasura allows the socket connection to start. However, hasura does not respond in the short time graphqurl expects, within a second or two, so graphqurl throws.

**Review by tk-vincit — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut)

**Review by tk-vincit — APPROVED** [review]
> docker-compose up --build
I don't think this causes any problems for me. For me it is OK to merge this.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/22#-:-MVSWo264Xrgu7XLGuVl:b-c37boo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut)

**Pull request merged**
