### PR TITLE
Approve Dependabot PRs automatically

### PR DESCRIPTION
**Pull request by haphut**
As we require reviews for PRs, Dependabot [cannot automerge its own PRs](https://github.com/HSLdevcom/jore4/issues/111#issuecomment-851393791). One solution is to create an approving review for pull requests from Dependabot automatically.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94)

### CODE REVIEW

**Comment by haphut** [comment]
I'm testing this yaml in production. :stuck_out_tongue: I find it easier to fix once it actually runs and breaks.

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94)* status: all files reviewed, 1 unresolved discussion (waiting on @haphut and @pallost)

___
*[.github/workflows/approve-dependabot.yml, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94#-Mb5wyc60V5TPE28m0Nf:-Mb5wyc60V5TPE28m0Ng:b-k5wxb7) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/fcf865093e2f342962af6ae26b6ed08872c39aad/.github/workflows/approve-dependabot.yml#L14)):*
> ```
> latest
> ```

Should we use a specific ubuntu version?

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @lassemaatta and @pallost)

___
*[.github/workflows/approve-dependabot.yml, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94#-Mb5wyc60V5TPE28m0Nf:-Mb6LrXF3bVrOBmA9pl-:b-wgvwfs) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/fcf865093e2f342962af6ae26b6ed08872c39aad/.github/workflows/approve-dependabot.yml#L14)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> latest
> ```

Should we use a specific ubuntu version?
</blockquote></details>

Thanks! I thought this particular yaml might stay working without touching it longer this way but I guess the argument is no different for any other action of ours. So I changed it to `ubuntu-20.04` for consistency.

**Review by pallost — APPROVED** [review]
The dependabot workflow looks good (after fixing the ubuntu version), I don't know enough about graphql schemas to comment on that part though

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94#-:-Mb6MnHS0d-zj0QjrG1q:b-uw2zt0)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut)

**Review by haphut — COMMENTED** [review]
Thanks! `graphqurl` output changed, that's all. Merging.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94#-:-Mb_O2PU65LexDFpBfvY:b-m4yvq7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut)

___
*[.github/workflows/approve-dependabot.yml, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/94#-Mb5wyc60V5TPE28m0Nf:-Mb6MvWo3MVEnbDB-IwT:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/fcf865093e2f342962af6ae26b6ed08872c39aad/.github/workflows/approve-dependabot.yml#L14)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Thanks! I thought this particular yaml might stay working without touching it longer this way but I guess the argument is no different for any other action of ours. So I changed it to `ubuntu-20.04` for consistency.
</blockquote></details>

Done.

**Pull request merged**
