### PR TITLE
CD

### PR DESCRIPTION
**Pull request by tk-vincit**
- Frontin docker-kuvien buildaus & puskeminen docker hubiin
- Tämä on tehty PR #20 :n päälle, joka valitettavasti on jäänyt vähän roikkumaan. Siispä siihen kuuluvia committeja ei kannata tässä yhteydessä katselmoida.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @haphut, @lassemaatta, and @tk-vincit)

___
*[frontend/Dockerfile, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVPltM-BdT1ytFXaJyP:-MVPltM-BdT1ytFXaJyQ:b-6xs259) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/7fc431da1162d5c8ea0f6eb219ea2dad9927bf32/frontend/Dockerfile#L2)):*
> ```Dockerfile
> FROM node:15.8.0-alpine3.12 AS build
> RUN apk --no-cache add curl
> ```

Could you add this to the beginning of the Dockerfile?
`ARG REACT_APP_GIT_HASH=unknown`

This would create a docker build parameter that creates a REACT_APP_GIT_HASH environment variable. That environment variable could that be displayed in the footer of the page. Usage: `docker build --build-arg REACT_APP_GIT_HASH=1d541312a`. It has a default value of "unknown", so even if you don't set the parameter, it will have a value.

In case the build arg does not directly get exposed to yarn build as an environment variable, you might need to manually expose it like this:
`RUN REACT_APP_GIT_HASH=$REACT_APP_GIT_HASH yarn build`

**Review by pallost — APPROVED** [review]
> Reviewed 9 of 24 files at r1, 1 of 12 files at r2, 4 of 9 files at r5, 1 of 2 files at r6, 5 of 5 files at r11, 3 of 3 files at r12, 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30)* status: all files reviewed, 14 unresolved discussions (waiting on @haphut, @lassemaatta, and @tk-vincit)

___
*[README.md, line 51 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpJo4WBB_ZAZyVjII3:-MVpJo4WBB_ZAZyVjII4:bavdojx) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/README.md#L51)):*
> ```Markdown
> 1. Run `hasura metadata ...` to read or write Hasura configuration.
> 
> To iterate on the frontend faster, run `docker compose up hasura` in project root and `yarn start` in `frontend` directory.
> ```

`docker-compose up -d hasura`?
___
*[.github/workflows/cd.yml, line 1 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpJQXj3nUUT91gGXK_:-MVpJQXj3nUUT91gGXKa:bilxktm) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/cd.yml#L1)):*
> ```YAML
> name: CD
> ```

ainakin mun termeissä CD tarkoittaa että tapahtuuko jotain muutos palvelimeissa, mutta tässä vaan rakennetaan kuvat. Mun mielestä tätä voisi kutsua mielummin "Docker Build & Push" workflowksi
___
*[.github/workflows/cd.yml, line 7 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpHPsh6Um-xLwC_xtt:-MVpHPsiCwsKLXXY6VPM:b-2k4rhu) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/cd.yml#L7)):*
> ```YAML
>     branches:
>       - main
>       - cd-test
> ```

tätä cd-testiä voisit tästä poistaa
___
*[.github/workflows/cd.yml, line 24 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpHgSz8RcOgWWQEbJj:-MVpHgSz8RcOgWWQEbJk:b-nyp717) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/cd.yml#L24)):*
> ```YAML
> 
>       - name: Pull previous image to support caching
>         run: docker pull $FRONTEND_IMAGE:builder
> ```

`docker pull $FRONTEND_IMAGE:builder || echo "Previous builder image not found"`, niin tämä ei kaadu jos kakkua ei löydy
___
*[.github/workflows/cd.yml, line 49 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpIMSgABpLylcj5Ce7:-MVpIMShCH7TPvRhWQMO:bgcm5hi) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/cd.yml#L49)):*
> ```YAML
> 
>       - name: Push dev build to Docker Hub
>         run: docker push $FRONTEND_IMAGE:$BRANCH_NAME-$GITHUB_SHA
> ```

varmaan pitäisi aina puskea:
:branch_name-github-sha
:builder

ja pusketaan vain jos pull requ meni läpi:
:dev
:latest
___
*[.github/workflows/cd.yml, line 53 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpIk8M5ZpVhVN_Jdey:-MVpIk8M5ZpVhVN_Jdez:bbknt0p) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/cd.yml#L53)):*
> ```YAML
>       - name: Push all tags to Docker Hub
>         if: ${{ github.ref == 'refs/heads/main' }}
>         run: docker push $FRONTEND_IMAGE --all-tags
> ```

mun mielestä kannattaa erotellä mitkä tägejä haluatko puskea Docker Hubiin, --all-tags vahingossa voisi puskea semmosia kuviakin jotka eivät ole tarkoitettu Docker Hubiin
___
*[.github/workflows/ci.yml, line 6 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpJvIG1KYU-Jr-dJBN:-MVpJvIG1KYU-Jr-dJBO:bgoyeob) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/ci.yml#L6)):*
> ```YAML
>   push:
>     branches:
>       - ci-test
> ```

branches: main?
___
*[.github/workflows/ci.yml, line 57 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpKEzb3MUHZaqRh3D6:-MVpKEzb3MUHZaqRh3D7:bkim31o) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/ci.yml#L57)):*
> ```YAML
> 
>       - name: Run tests
>         run: yarn test --ci
> ```

varmaan tätä kannattaa wrapata omaan scriptiin package jsonissa: `"test:ci": "yarn test --ci"`. Koska nyt jos vahingossa muokaamme jotain perus "yarn test" scriptissä, unohtuu että CI:kin haluaisi kutsua juuri sitä
___
*[frontend/Dockerfile, line 1 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpKt6V3wMjeWetxmFC:-MVpKt6V3wMjeWetxmFD:b1n9ad2) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/frontend/Dockerfile#L1)):*
> ```Dockerfile
> FROM node:15.8.0-alpine3.12 AS build
> ```

komennot ovat oikeassa järjestyksessä, niin kakutus on hyvin optimoitu. Hyvin tehty!
___
*[frontend/package.json, line 29 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpLH6QDdV8VYX7MbP1:-MVpLH6QDdV8VYX7MbP2:b-n0ve7u) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/frontend/package.json#L29)):*
> ```JSON
>   },
>   "scripts": {
>     "start": "yarn prebuild && REACT_APP_BACKEND_HOST=localhost:8080 react-scripts start",
> ```

ei sinun pitäisi tarvita tätä REACT_APP_BACKEND_HOST parametria enää kun hasura jo näkyy nginx proxyn kautta. Käytännössä siis frontend ja hasura ovat aina saman hostin alla, niin frontend voisi viittata `/v1beta1/relay` reittiin, ei tartte viittata `http://localhost:8080/v1beta1/relay` osoitteeseen
___
*[frontend/src/App.tsx, line 20 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpM6-IA-e4Q6Orbhb6:-MVpM6-IA-e4Q6Orbhb7:bnpsmlr) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/frontend/src/App.tsx#L20)):*
> ```XML
>       <footer>
>         <p>Click on the map to insert a new point into the database.</p>
>         <p>Version: {process.env.REACT_APP_GIT_HASH}</p>
> ```

kiitos!
___
*[frontend/src/components/CircleLayer.tsx, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpN6gCDYT7vcGCw6w1:-MVpN6gCDYT7vcGCw6w2:bonf33p) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/7fc431da1162d5c8ea0f6eb219ea2dad9927bf32/frontend/src/components/CircleLayer.tsx#L9)):*
> ```XML
> import { updatePoint } from "./mutations/UpdatePoint";
> 
> const SUBSCRIBE_ALL_POINTS = graphql`
> ```

vain oma pohdinta tässä että käytännössä tämä graphql kysely on:
1. selector, koska osaa kakutetusta datasta hakea tarvitut kamat itselle
2. api kutsu, koska jos jotain data ei löydy, sitten osaa hakea itselle hasurasta
mutta ei kumpikaan kuulu componentiin.

Kun en osaa sanoa että mihin se sitten mielummin kuuluu, mun puolesta sekin on OK jos jätän vain tänne :D
___
*[frontend/src/components/mutations/DeletePoint.ts, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpMwzHETgaguPQ7B8L:-MVpMwzHETgaguPQ7B8M:bgbh3vu) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/7fc431da1162d5c8ea0f6eb219ea2dad9927bf32/frontend/src/components/mutations/DeletePoint.ts#L1)):*
> ```XML
> import graphql from "babel-plugin-relay/macro"; // https://create-react-app.dev/docs/adding-relay/
> ```

sama pohdinta, mun mielestä mutaatiot eivät kuulu "components" kansioon, mielummin johonkin "api" kansioon...
___
*[frontend/src/utils/index.ts, line 1 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpMG55DjM4vHpKzrUg:-MVpMG55DjM4vHpKzrUh:bgon32x) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/frontend/src/utils/index.ts#L1)):*
> ```XML
> export const getWsUri = () => {
> ```

tämä mun mielestä kuuluu mielummin johonkin "config" nimiseen tiedostoon

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30)* status: all files reviewed, 14 unresolved discussions (waiting on @haphut, @lassemaatta, @pallost, and @tk-vincit)

___
*[README.md, line 51 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpJo4WBB_ZAZyVjII3:-MVpP1et-EJokm01Kn1Q:b-qrjabz) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/README.md#L51)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`docker-compose up -d hasura`?
</blockquote></details>

As you wish
___
*[.github/workflows/cd.yml, line 1 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpJQXj3nUUT91gGXK_:-MVpWWOQEEXbou_gp0I2:b-rz9dn3) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/cd.yml#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

ainakin mun termeissä CD tarkoittaa että tapahtuuko jotain muutos palvelimeissa, mutta tässä vaan rakennetaan kuvat. Mun mielestä tätä voisi kutsua mielummin "Docker Build & Push" workflowksi
</blockquote></details>

No, voihan tämän ajatella niinkin, että tässä "deployataan" docker imaget docker hubiin... Mutta joo, nimetään uudelleen. Tiedostonnimen taidan kyllä jättää toistaiseksi näin kun ei nyt suorilta tule parempiakaan ideoita.
___
*[.github/workflows/cd.yml, line 7 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpHPsh6Um-xLwC_xtt:-MVpPIMKC5yfBxxo06vp:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/cd.yml#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

tätä cd-testiä voisit tästä poistaa
</blockquote></details>

Done.
___
*[.github/workflows/cd.yml, line 24 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpHgSz8RcOgWWQEbJj:-MVpPUyC2gkjBJn36LZf:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/cd.yml#L24)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`docker pull $FRONTEND_IMAGE:builder || echo "Previous builder image not found"`, niin tämä ei kaadu jos kakkua ei löydy
</blockquote></details>

Done.
___
*[.github/workflows/ci.yml, line 6 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpJvIG1KYU-Jr-dJBN:-MVpV8UK5eEb2YSViojX:b2nhktp) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/.github/workflows/ci.yml#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

branches: main?
</blockquote></details>

OK.
___
*[frontend/Dockerfile, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVPltM-BdT1ytFXaJyP:-MVR0lYG8RWl4_32j8YP:bvxurpp) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/7fc431da1162d5c8ea0f6eb219ea2dad9927bf32/frontend/Dockerfile#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Could you add this to the beginning of the Dockerfile?
`ARG REACT_APP_GIT_HASH=unknown`

This would create a docker build parameter that creates a REACT_APP_GIT_HASH environment variable. That environment variable could that be displayed in the footer of the page. Usage: `docker build --build-arg REACT_APP_GIT_HASH=1d541312a`. It has a default value of "unknown", so even if you don't set the parameter, it will have a value.

In case the build arg does not directly get exposed to yarn build as an environment variable, you might need to manually expose it like this:
`RUN REACT_APP_GIT_HASH=$REACT_APP_GIT_HASH yarn build`
</blockquote></details>

I guess that there wasn't specific need to add this specifictly in the beginning of the dockerfile, as it invalidates cache for the whole docker file for every single PR as git commit hash changes every time?

Anyway, added that step just before build step and verified locally that it works.

(Of course we now have to do fresh build on every pr even if code itself is not changed, but maybe we can live with that.
___
*[frontend/Dockerfile, line 1 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpKt6V3wMjeWetxmFC:-MVpSxNF9gG5PasNeXAV:b-xg55i8) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/frontend/Dockerfile#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

komennot ovat oikeassa järjestyksessä, niin kakutus on hyvin optimoitu. Hyvin tehty!
</blockquote></details>

Tänks!
___
*[frontend/src/components/CircleLayer.tsx, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpN6gCDYT7vcGCw6w1:-MVpTDQxAZ1B5e-XMwd3:b-21mq6o) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/7fc431da1162d5c8ea0f6eb219ea2dad9927bf32/frontend/src/components/CircleLayer.tsx#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

vain oma pohdinta tässä että käytännössä tämä graphql kysely on:
1. selector, koska osaa kakutetusta datasta hakea tarvitut kamat itselle
2. api kutsu, koska jos jotain data ei löydy, sitten osaa hakea itselle hasurasta
mutta ei kumpikaan kuulu componentiin.

Kun en osaa sanoa että mihin se sitten mielummin kuuluu, mun puolesta sekin on OK jos jätän vain tänne :D
</blockquote></details>

Jeps, tämä ei tosiaan ole optimaalisesti toteutettu. Parannuksia tulee seuraavassa pull requssa. 
___
*[frontend/src/components/mutations/DeletePoint.ts, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpMwzHETgaguPQ7B8L:-MVpYsFu-cAACSjkpA1a:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/7fc431da1162d5c8ea0f6eb219ea2dad9927bf32/frontend/src/components/mutations/DeletePoint.ts#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

sama pohdinta, mun mielestä mutaatiot eivät kuulu "components" kansioon, mielummin johonkin "api" kansioon...
</blockquote></details>

OK
___
*[frontend/src/utils/index.ts, line 1 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpMG55DjM4vHpKzrUg:-MVpYnsv8eQghQ8bZtI6:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/frontend/src/utils/index.ts#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

tämä mun mielestä kuuluu mielummin johonkin "config" nimiseen tiedostoon
</blockquote></details>

OK

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 2 of 24 files at r1, 1 of 12 files at r2, 2 of 9 files at r5, 1 of 2 files at r6, 5 of 5 files at r11, 3 of 3 files at r12, 3 of 3 files at r13, 6 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30)* status: all files reviewed, 14 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @haphut, @lassemaatta, and @tk-vincit)

___
*[README.md, line 51 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpJo4WBB_ZAZyVjII3:-MVpv5xHD2tuB5Nc22im:b-1xguhx) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/README.md#L51)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

As you wish
</blockquote></details>

`docker-compose` needs a dash :)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @haphut, @lassemaatta, @pallost, and @tk-vincit)

___
*[README.md, line 51 at r13](https://reviewable.io/reviews/hsldevcom/jore4-graphql-playground/30#-MVpJo4WBB_ZAZyVjII3:-MVqxgMMBB6QON2WSZIN:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-graphql-playground/blob/04ac9642576e259ecd30f05c55bad85a7d11a59b/README.md#L51)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`docker-compose` needs a dash :)
</blockquote></details>

Done.

**Pull request merged**
